### ISSUE TITLE
Crash upon login on Android 15

### ISSUE THREAD

**Issue by MrFrog222** [Aliucord/Aliucord#506]
### What happens when the bug or crash occurs?

Everytime I open the app, it crashes saying ```An unrecoverable crash occured```. Furthermore upon reinstalling or clearing data it works at first but as soon as you log in the same crash happens.

### What is the expected behaviour?

I expect Aliucord to bring me to the main page instead of crashing.

### How do you recreate this bug or crash?

1. Install the latest version of Aliucord
2. Try logging in

### Crash-log

```
I know it is difficult to find the issue without a crash log but i am unable to retrieve it as Aliucord always crashes before i can get to the settings screen.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by mantikafasi** [comment]
whats your rom, also get your crash log from files/Aliucord/

**Comment by MrFrog222** [comment]
My Rom is LineageOS 22.1 without Gapps on the Fairphone 5

**Comment by flopenN** [comment]
Same thing happens to me on the xiaomi.eu rom, version 2.0.3.0VNCCNXM (Android 15)

will this be fixed in the near future?

**Comment by ShootingKing-AM** [comment]
Same with me, its kind a weird in the sense, Fresh Install (lable: **start**) -> Login -> It works for some time max a day and again if you open it crahes on login -> Clear Storage and Cache -> Still Crashes -> Uninstall the app -> From AluInstalled install again -> goto label **start**

Full Logcat
```java
23:26:38.387  9511-9511  com.aliucord                                       com.aliucord                         I  Using CollectorTypeCC GC.
23:26:39.481  9511-9511  AliuHook                                           com.aliucord                         W  found symtab /apex/com.android.art/lib64/libart.so
23:26:39.711  9511-9511  AliuHook                                           com.aliucord                         I  lsplant init finished
23:26:40.017  9511-9511  FirebaseApp                                        com.aliucord                         I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
23:26:40.237  9511-9581  com.aliucord                                       com.aliucord                         W  ClassLoaderContext classpath size mismatch. expected=1, found=0 (DLC[];PCL[base.apk*2660165478]{PCL[/system/framework/org.apache.http.legacy.jar*130603114]#PCL[/system/framework/com.android.media.remotedisplay.jar*237911948]#PCL[/system/framework/com.android.location.provider.jar*3688387286]#PCL[/system_ext/framework/androidx.window.extensions.jar*1629019302]#PCL[/system_ext/framework/androidx.window.sidecar.jar*596506100]} | DLC[];PCL[])
23:26:40.281  9511-9581  com.aliucord                                       com.aliucord                         W  ClassLoaderContext classpath element checksum mismatch. expected=2660165478, found=2647844148 (DLC[];PCL[base.apk*2660165478]{PCL[/system/framework/org.apache.http.legacy.jar*130603114]#PCL[/system/framework/com.android.media.remotedisplay.jar*237911948]#PCL[/system/framework/com.android.location.provider.jar*3688387286]#PCL[/system_ext/framework/androidx.window.extensions.jar*1629019302]#PCL[/system_ext/framework/androidx.window.sidecar.jar*596506100]} | DLC[];PCL[/data/app/~~tswfcd74nbCI8hHUaX0v0w==/com.aliucord-8dRByHVL7i4K-SRnsXYJkw==/base.apk*2647844148]{PCL[/system/framework/android.test.base.jar*1888548828]})
23:26:40.328  9511-9511  FirebaseInitProvider                               com.aliucord                         I  FirebaseApp initialization successful
23:26:40.355  9511-9601  com.aliucord                                       com.aliucord                         E  No package ID 76 found for resource ID 0x760b000f.
23:26:40.567  9511-9511  Adjust                                             com.aliucord                         W  PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
23:26:40.567  9511-9511  Adjust                                             com.aliucord                         W  PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
23:26:41.379  9511-9511  fb-UnpackingSoSource                               com.aliucord                         I  dso store is up-to-date: /data/user/0/com.aliucord/lib-main
23:26:41.647  9511-9623  Discord                                            com.aliucord                         I  [Persister] Preloaded preferences in 0.694 seconds.
23:26:41.692  9511-9511  Discord                                            com.aliucord                         I  Application initialized.
23:26:41.699  9511-9511  Discord                                            com.aliucord                         W  NotificationClient -> FCM token was not sent to server
23:26:41.728  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1300914562685472869,991300258082590823, receiving_user_id=317716017931485195}
23:26:41.745  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1308528233024847963, receiving_user_id=317716017931485195}
23:26:41.764  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1141147227335692330, receiving_user_id=317716017931485195}
23:26:41.781  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1183691771910303744, receiving_user_id=317716017931485195}
23:26:41.806  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1009028320257638440, receiving_user_id=317716017931485195}
23:26:41.818  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1328420899312898089, receiving_user_id=317716017931485195}
23:26:41.830  9511-9643  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=848447987755646986, receiving_user_id=317716017931485195}
23:28:31.098  9511-9684  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1269714749784985787, receiving_user_id=317716017931485195}
23:38:35.624  9511-9744  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1146149533756162108, receiving_user_id=317716017931485195}
23:38:36.920  9511-9744  Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1300914562685472869, receiving_user_id=317716017931485195}
23:46:22.233  9511-9511  Discord                                            com.aliucord                         I  Application activity initialized.
23:46:22.392  9511-10024 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:46:22.399  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onAvailable fired: 100
23:46:22.401  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:46:22.401  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:46:22.404  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:46:22.501  9511-9511  AliuHook                                           com.aliucord                         E  Symbol _ZN3art12ProfileSaver20ProcessProfilingInfoEbbPt not found in elf libart.so
23:46:22.501  9511-9511  AliuHook                                           com.aliucord                         E  Failed to disable ProfileSaver: ProfileSaver::ProcessProfilingInfo not found
23:46:22.502  9511-9511  Discord                                            com.aliucord                         W  [Injector] Failed to disable profile saver
23:46:22.613  9511-9623  Discord                                            com.aliucord                         I  [MessageLoader] Loaded detached channel state: []
23:46:22.694  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /data/user/0/com.aliucord/code_cache/Aliucord.zip
23:46:22.810  9511-10024 Discord                                            com.aliucord                         I  [StoreStream] Application stores initialized in: 0.436 seconds.
23:46:22.891  9511-10024 Discord                                            com.aliucord                         I  [StoreStream] Application backgrounded: true
23:46:22.893  9511-10041 Discord                                            com.aliucord                         W  AudioPermissions -> RECORD_AUDIO permission is missing
23:46:22.893  9511-10041 Discord                                            com.aliucord                         W  DiscordAudioManager -> Unable to activate audio output outside Discord-requested communication mode
23:46:22.896  9511-10041 Discord                                            com.aliucord                         W  DiscordAudioManager -> Unable to releaseAudioFocus()
23:46:22.994  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: ButtonsAPI
23:46:22.996  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: CommandHandler
23:46:23.006  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: CoreCommands
23:46:23.006  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: DefaultStickers
23:46:23.006  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: ExperimentDefaults
23:46:23.006  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: GifPreviewFix
23:46:23.008  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: MembersListFix
23:46:23.011  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: NoTrack
23:46:23.045  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: PluginDownloader
23:46:23.046  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: PrivateChannelsListScroll
23:46:23.047  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: PrivateThreads
23:46:23.047  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: RNAPI
23:46:23.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: Pronouns
23:46:23.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: SupportWarn
23:46:23.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: SupporterBadges
23:46:23.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: TokenLogin
23:46:23.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading coreplugin: UploadSize
23:46:23.113  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: AccountSwitcher
23:46:23.116  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/AccountSwitcher.zip
23:46:23.133  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: BetterStatusIndicators
23:46:23.134  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/BetterStatusIndicators.zip
23:46:23.158  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: CallTime
23:46:23.158  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/CallTime.zip
23:46:23.172  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: CheckLinks
23:46:23.173  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/CheckLinks.zip
23:46:23.189  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ClickableMentions
23:46:23.190  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ClickableMentions.zip
23:46:23.213  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: DedicatedPluginSettings
23:46:23.214  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/DedicatedPluginSettings.zip
23:46:23.231  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: FakeStickers
23:46:23.232  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/FakeStickers.zip
23:46:23.252  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ForceNotifications
23:46:23.253  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ForceNotifications.zip
23:46:23.264  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: GuildProfiles
23:46:23.265  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/GuildProfiles.zip
23:46:23.283  9511-9626  AndroidRuntime                                     com.aliucord                         E  FATAL EXCEPTION: RxComputationScheduler-4
                                                                                                                    Process: com.aliucord, PID: 9511
                                                                                                                    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                                                    	at j0.l.c.j.run(ScheduledAction.java:3)
                                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:347)
                                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                                    	at java.lang.Thread.run(Thread.java:1117)
                                                                                                                    Caused by: java.lang.ClassCastException: com.aliucord.api.rn.user.RNUser cannot be cast to java.lang.Throwable
                                                                                                                    	at j0.l.a.x0$e.h(OperatorMerge.java:3)
                                                                                                                    	at j0.l.a.x0$e.a(OperatorMerge.java:4)
                                                                                                                    	at j0.l.a.x0$e.c(OperatorMerge.java:2)
                                                                                                                    	at j0.l.a.x0$e.b(OperatorMerge.java:7)
                                                                                                                    	at j0.l.a.x0$e.onError(OperatorMerge.java:3)
                                                                                                                    	at j0.l.a.s$a.onError(OnSubscribeMap.java:4)
                                                                                                                    	at j0.l.a.z0$a.a(OperatorObserveOn.java:10)
                                                                                                                    	at j0.l.a.z0$a.call(OperatorObserveOn.java:7)
                                                                                                                    	at j0.l.c.b$a$a.call(EventLoopsScheduler.java:4)
                                                                                                                    	at j0.l.c.j.run(ScheduledAction.java:2)
                                                                                                                    	... 6 more
23:46:23.327  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: MessageLinkEmbeds
23:46:23.328  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/MessageLinkEmbeds.zip
23:46:23.342  9511-9511  com.aliucord                                       com.aliucord                         I  Waiting for a blocking GC ClassLinker
23:46:23.654  9511-9515  com.aliucord                                       com.aliucord                         I  Background concurrent copying GC freed 27MB AllocSpace bytes, 725(15MB) LOS objects, 66% free, 12MB/37MB, paused 220us,71us total 340.483ms
23:46:23.655  9511-9511  com.aliucord                                       com.aliucord                         I  WaitForGcToComplete blocked ClassLinker on Background for 312.871ms
23:46:23.660  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: NitroSpoof
23:46:23.662  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/NitroSpoof.zip
23:46:23.680  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: PersistSettings
23:46:23.681  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/PersistSettings.zip
23:46:23.695  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: PluginRepo
23:46:23.696  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/PluginRepo.zip
23:46:23.714  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: RemoveZoomLimit
23:46:23.715  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/RemoveZoomLimit.zip
23:46:23.729  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ReverseImageSearch
23:46:23.729  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ReverseImageSearch.zip
23:46:23.750  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ThemeRepo
23:46:23.751  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ThemeRepo.zip
23:46:23.765  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: Translate
23:46:23.765  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/Translate.zip
23:46:23.785  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: UserDetails
23:46:23.786  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/UserDetails.zip
23:46:23.820  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ValidUser
23:46:23.821  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ValidUser.zip
23:46:23.849  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ViewProfileImages
23:46:23.851  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ViewProfileImages.zip
23:46:23.875  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ViewRaw
23:46:23.879  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ViewRaw.zip
23:46:23.927  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Loading plugin: ViewStreamPreview
23:46:23.928  9511-9511  com.aliucord                                       com.aliucord                         E  Attempt to load writable dex file: /storage/emulated/0/Aliucord/plugins/ViewStreamPreview.zip
23:46:23.955  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ButtonsAPI
23:46:23.955  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ButtonsAPI in 0 milliseconds
23:46:23.955  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: CommandHandler
23:46:23.955  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: CommandHandler in 0 milliseconds
23:46:23.960  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: CoreCommands
23:46:23.962  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: CoreCommands in 2 milliseconds
23:46:23.962  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: DefaultStickers
23:46:23.968  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: DefaultStickers in 6 milliseconds
23:46:23.968  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ExperimentDefaults
23:46:23.971  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ExperimentDefaults in 3 milliseconds
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: GifPreviewFix
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: GifPreviewFix in 0 milliseconds
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: MembersListFix
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: MembersListFix in 0 milliseconds
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: NoTrack
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: NoTrack in 0 milliseconds
23:46:23.972  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: PluginDownloader
23:46:23.976  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: PluginDownloader in 3 milliseconds
23:46:23.976  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: PrivateChannelsListScroll
23:46:23.976  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: PrivateChannelsListScroll in 0 milliseconds
23:46:23.976  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: PrivateThreads
23:46:23.981  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: PrivateThreads in 5 milliseconds
23:46:23.981  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: RNAPI
23:46:23.981  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: RNAPI in 0 milliseconds
23:46:23.981  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: Pronouns
23:46:23.982  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: Pronouns in 1 milliseconds
23:46:23.984  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: SupportWarn
23:46:23.997  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: SupportWarn in 13 milliseconds
23:46:23.997  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: SupporterBadges
23:46:24.009  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: SupporterBadges in 12 milliseconds
23:46:24.009  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: TokenLogin
23:46:24.013  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: TokenLogin in 4 milliseconds
23:46:24.013  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: UploadSize
23:46:24.022  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: UploadSize in 9 milliseconds
23:46:24.023  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: AccountSwitcher
23:46:24.026  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: AccountSwitcher in 3 milliseconds
23:46:24.026  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: BetterStatusIndicators
23:46:24.066  9511-9511  com.aliucord                                       com.aliucord                         W  Suspending all threads took: 5.946ms
23:46:24.086  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: BetterStatusIndicators in 60 milliseconds
23:46:24.086  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: CallTime
23:46:24.091  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: CallTime in 5 milliseconds
23:46:24.091  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: CheckLinks
23:46:24.095  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: CheckLinks in 4 milliseconds
23:46:24.095  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ClickableMentions
23:46:24.100  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ClickableMentions in 4 milliseconds
23:46:24.100  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: DedicatedPluginSettings
23:46:24.103  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: DedicatedPluginSettings in 3 milliseconds
23:46:24.103  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: FakeStickers
23:46:24.107  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: FakeStickers in 4 milliseconds
23:46:24.107  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ForceNotifications
23:46:24.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ForceNotifications in 2 milliseconds
23:46:24.109  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: GuildProfiles
23:46:24.113  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: GuildProfiles in 4 milliseconds
23:46:24.113  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: MessageLinkEmbeds
23:46:24.116  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: MessageLinkEmbeds in 3 milliseconds
23:46:24.116  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: NitroSpoof
23:46:24.123  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: NitroSpoof in 7 milliseconds
23:46:24.123  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: PersistSettings
23:46:24.124  9511-9511  Discord                                            com.aliucord                         E  [PluginManager] Exception while starting plugin: PersistSettings
23:46:24.125  9511-9511  Discord                                            com.aliucord                         E  java.lang.NoSuchFieldException: No field authToken in class Lcom/discord/stores/StoreAuthentication; (declaration of 'com.discord.stores.StoreAuthentication' appears in /data/app/~~tswfcd74nbCI8hHUaX0v0w==/com.aliucord-8dRByHVL7i4K-SRnsXYJkw==/base.apk!classes3.dex)
                                                                                                                    	at java.lang.Class.getDeclaredField(Native Method)
                                                                                                                    	at com.aliucord.plugins.PersistSettings.start(PersistSettings.java:61)
                                                                                                                    	at com.aliucord.PluginManager.startPlugin(PluginManager.java:167)
                                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                    	at de.robv.android.xposed.XposedBridge.invokeMethod(XposedBridge.java:243)
                                                                                                                    	at de.robv.android.xposed.XposedBridge.-$$Nest$sminvokeMethod(Unknown Source:0)
                                                                                                                    	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:369)
                                                                                                                    	at LSPHooker_.startPlugin(Unknown Source:8)
                                                                                                                    	at com.aliucord.Main.startAllPlugins(Main.java:423)
                                                                                                                    	at com.aliucord.Main.init(Main.java:293)
                                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                    	at com.aliucord.injector.InjectorKt.init(Injector.kt:116)
                                                                                                                    	at
23:46:24.125  9511-9511  Discord                                            com.aliucord                         E   com.aliucord.injector.InjectorKt.access$init(Injector.kt:1)
                                                                                                                    	at com.aliucord.injector.InjectorKt$init$1.beforeHookedMethod(Injector.kt:43)
                                                                                                                    	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:352)
                                                                                                                    	at LSPHooker_.onCreate(Unknown Source:11)
                                                                                                                    	at android.app.Activity.performCreate(Activity.java:9019)
                                                                                                                    	at android.app.Activity.performCreate(Activity.java:8997)
                                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1528)
                                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
                                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4316)
                                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
                                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
                                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
                                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionEx
23:46:24.125  9511-9511  Discord                                            com.aliucord                         E  ecutor.java:80)
                                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
                                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8782)
                                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
                                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
23:46:24.125  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: PluginRepo
23:46:24.140  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: PluginRepo in 15 milliseconds
23:46:24.140  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: RemoveZoomLimit
23:46:24.145  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: RemoveZoomLimit in 5 milliseconds
23:46:24.145  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ReverseImageSearch
23:46:24.147  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ReverseImageSearch in 2 milliseconds
23:46:24.147  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ThemeRepo
23:46:24.147  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ThemeRepo in 0 milliseconds
23:46:24.147  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: Translate
23:46:24.153  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: Translate in 6 milliseconds
23:46:24.154  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: UserDetails
23:46:24.159  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: UserDetails in 5 milliseconds
23:46:24.159  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ValidUser
23:46:24.162  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ValidUser in 3 milliseconds
23:46:24.162  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ViewProfileImages
23:46:24.170  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ViewProfileImages in 8 milliseconds
23:46:24.170  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ViewRaw
23:46:24.173  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ViewRaw in 2 milliseconds
23:46:24.173  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Starting plugin: ViewStreamPreview
23:46:24.177  9511-9511  Discord                                            com.aliucord                         I  [PluginManager] Started plugin: ViewStreamPreview in 4 milliseconds
23:46:24.318  9511-9511  Discord                                            com.aliucord                         I  [NetworkMonitor] -> Got connectivity action broadcast intent.
23:46:24.320  9511-9511  Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:40.385  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:40.388  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:46.571  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:46.574  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:49.651  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:49.653  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:52.750  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:52.752  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:55.848  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:55.850  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:47:58.926  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Network callback, onCapabilitiesChanged fired: 100
23:47:58.930  9511-10025 Discord                                            com.aliucord                         I  [NetworkMonitor] -> Updating network state to ONLINE, API: 35
23:49:09.526 10305-10305 AliuHook                                           com.aliucord                         W  found symtab /apex/com.android.art/lib64/libart.so
23:49:09.624 10305-10305 AliuHook                                           com.aliucord                         I  lsplant init finished
23:49:09.705 10305-10305 FirebaseApp                                        com.aliucord                         I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
23:49:09.786 10305-10324 com.aliucord                                       com.aliucord                         W  ClassLoaderContext classpath size mismatch. expected=1, found=0 (DLC[];PCL[base.apk*2660165478]{PCL[/system/framework/org.apache.http.legacy.jar*130603114]#PCL[/system/framework/com.android.media.remotedisplay.jar*237911948]#PCL[/system/framework/com.android.location.provider.jar*3688387286]#PCL[/system_ext/framework/androidx.window.extensions.jar*1629019302]#PCL[/system_ext/framework/androidx.window.sidecar.jar*596506100]} | DLC[];PCL[])
23:49:09.850 10305-10324 com.aliucord                                       com.aliucord                         W  ClassLoaderContext classpath element checksum mismatch. expected=2660165478, found=2647844148 (DLC[];PCL[base.apk*2660165478]{PCL[/system/framework/org.apache.http.legacy.jar*130603114]#PCL[/system/framework/com.android.media.remotedisplay.jar*237911948]#PCL[/system/framework/com.android.location.provider.jar*3688387286]#PCL[/system_ext/framework/androidx.window.extensions.jar*1629019302]#PCL[/system_ext/framework/androidx.window.sidecar.jar*596506100]} | DLC[];PCL[/data/app/~~tswfcd74nbCI8hHUaX0v0w==/com.aliucord-8dRByHVL7i4K-SRnsXYJkw==/base.apk*2647844148]{PCL[/system/framework/android.test.base.jar*1888548828]})
23:49:09.934 10305-10329 com.aliucord                                       com.aliucord                         E  No package ID 76 found for resource ID 0x760b000f.
23:49:09.948 10305-10305 FirebaseInitProvider                               com.aliucord                         I  FirebaseApp initialization successful
23:49:10.116 10305-10305 Adjust                                             com.aliucord                         W  PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
23:49:10.116 10305-10305 Adjust                                             com.aliucord                         W  PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
23:49:10.412 10305-10305 fb-UnpackingSoSource                               com.aliucord                         I  dso store is up-to-date: /data/user/0/com.aliucord/lib-main
23:49:10.545 10305-10347 Discord                                            com.aliucord                         I  [Persister] Preloaded preferences in 0.414 seconds.
23:49:10.567 10305-10305 Discord                                            com.aliucord                         I  Application initialized.
23:49:10.573 10305-10305 Discord                                            com.aliucord                         W  NotificationClient -> FCM token was not sent to server
23:49:10.601 10305-10366 Discord                                            com.aliucord                         I  Got notification: {type=CHANNEL_ACK, channel_ids=1328420899312898089,811261298997460992, receiving_user_id=317716017931485195}
```

Relevant errors:
![image](https://github.com/user-attachments/assets/bef4b937-1d96-40ff-95ed-037296660acc)
![image](https://github.com/user-attachments/assets/b3bf706a-8909-4e85-ba06-932d5e4a7655)
![image](https://github.com/user-attachments/assets/c1a8ec37-bf91-4bb9-9f52-37e1b90b95fb)

**Comment by ShootingKing-AM** [comment]
Is the team investigating it is someone assigned for this ?

**Comment by ShootingKing-AM** [comment]
OK this is not a Aliucord's bug for me on my End. its the https://github.com/zt64/aliucord-plugins 's AccountSwitcher plugin, tested for 2days

**Comment by xswordcrash** [comment]
I don't have account switcher but is still crashing. I thought it was the theme repo turns out it's not. It was fine for like a day and then started crashing. Before that it was fine for like 5 days after reinstallation.

**Comment by xswordcrash** [comment]
> Please try installing aliu through the WIP manager: https://github.com/Aliucord/Manager/actions/runs/12785651330/artifacts/2433492324
> 
> see if it prevents the crash from reoccurring

So before to test if the client is crashing I would crash it once and it will never open again but the one with this WIP manager I crashed it a few times and it would open. Can probably say that it's fine now (hopefully). Although had some issues on the WIPanager, is it possible to add export option for the patched apk, I had to go to android/data and find the patched apk while the manager is stuck on installing since Xiaomi hates apps installing other apps for some reason, or uhh add shizuku support.

**Comment by ShootingKing-AM** [comment]
asdas

> ~OK this is not a Aliucord's bug for me on my End. its the https://github.com/zt64/aliucord-plugins 's AccountSwitcher plugin, tested for 2days~
> 

Nope It is crashing today again without account switcher - nothing actually changed from Day1 to day3

**Comment by rushiiMachine** [comment]
@ShootingKing-AM Have you tried doing what my comment says?

**Comment by ShootingKing-AM** [comment]
> [@ShootingKing-AM](https://github.com/ShootingKing-AM) Have you tried doing what my comment says?

Just installed, will need to wait for some time iguess. Installed stable 126.21 version

**Comment by ShootingKing-AM** [comment]
Ok it didn't crash till now. But accountswitcher plugin does crash on load

**Comment by rushiiMachine** [comment]
This issue is caused by a recent ART update which was distributed via Android 15 QPR1 and backported to versions down to Android 12 since ART is an Android mainline component.

I've already fixed this internally: https://github.com/Aliucord/hook/compare/25a79d4333ee352852da41703ce3d3384f617703...main

I can't deploy the fix until we release the new installer (aka. Manager).
If you want a temporary fix for Aliucord for now, reinstall with manager: https://nightly.link/Aliucord/Manager/workflows/build/main/app.zip
Note that when we actually release you will need to uninstall the debug version.

**Comment by silverwings15** [comment]
> I can't deploy the fix until we release the new installer (aka. Manager).

will this be out any time soon?

**Comment by emailtemptest53** [comment]
Model: Itel P55 5G
OS: Android 13
Ram: 6 GB 
Rom: 128 GB 

(I tried newer)
Aliucord installer: 1.2.0
Aliucord app: 126.21 - stable

(I used old)
Aliucord installer: 0.0.1 thingy 
Aliucord app: 126.1 - stable

One day I opened the app
In the video shown keep crashing like that

Fixes I did,
Reboot, clear data all, reinstall even redownload,
Remove settings, themes, plugins,
Still keep crashing or refreshing its own
Ram? I optimize no unnecessary running apps I got plenty of space 
Even the old still crashing 
I recorded two versions 


https://github.com/user-attachments/assets/a0814726-c2be-42db-9768-ac1e8e483712
https://github.com/user-attachments/assets/ac2a9277-2ed8-4b4f-95ca-6d00558e34cb

**Comment by rushiiMachine** [comment]
@emailtemptest53 duplicate of a separate issue https://github.com/Aliucord/Aliucord/issues/524

**Comment by ledfwil** [comment]
> Please try installing aliu through the WIP manager: https://github.com/Aliucord/Manager/actions/runs/12785651330/artifacts/2433492324
> 
> see if it prevents the crash from reoccurring 

Anybody have this file? The artifact expired.

**Comment by rushiiMachine** [comment]
Closing now since Manager has been released for a while by now.
